version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stderr
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gomodguard
    - inamedparam
    - ireturn
    - lll
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - perfsprint
    - promlinter
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gosec:
      excludes:
        - G115
    nlreturn:
      block-size: 3
    staticcheck:
      checks:
        - all
        - -ST1000
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    paths:
      - .*_ssz\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_ssz\.go$
      - third_party$
      - builtin$
      - examples$
